### ISSUE TITLE
Fails in install.js for Debian sid (aptosid distro) - code ELIFECYCLE

### ISSUE THREAD

**Issue by flipefr** [ProtonMail/WebClient#10]
> sudo npm install
npm WARN package.json protonmail-web@ No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.8
 
> phantomjs@1.9.18 install /home/flipefr/Desktop/WebClient-master/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.0.0-0.slh.3-aptosid-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/flipefr/Desktop/WebClient-master
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
 
> ws@0.4.32 install /home/flipefr/Desktop/WebClient-master/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
> node-sass@3.3.2 install /home/flipefr/Desktop/WebClient-master/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/flipefr/Desktop/WebClient-master/npm-debug.log
npm ERR! not ok code 0

File /home/flipefr/Desktop/WebClient-master/npm-debug.log in 
https://gist.github.com/flipefr/77f3cc1ecae1767cae44
or
https://gist.github.com/flipefr/77f3cc1ecae1767cae44/archive/89e21c1b0bb464e5aa768556d8a1f5bb54e0c60f.zip

**Comment by bartbutler** [comment]
Looks like you have npm installed by not node, somehow. Try 'which node' and see if something comes up.

**Comment by flipefr** [comment]
> which node
node not found

If I try

> sudo apt-get install node                                                                 
Leyendo lista de paquetes... Hecho  ==translated==  reading package list
Creando árbol de dependencias   ==translated==  creating dependencies tree
Leyendo la información de estado... Hecho   ==translated==  reading status info
node ya está en su versión más reciente.     ==translated==  node is already in the last version

when doing 
sudo npm install 
I ave the exact same output as above.

**Comment by bartbutler** [comment]
Make sure you have node installed and in your path ('which node' needs to show your node binary). If it still doesn't work, you should try using node v12, as that is the version we use. I don't think it's strictly necessary though.

**Comment by flipefr** [comment]
> sudo dpkg -l | grep node
ii  ax25-node                                                   0.3.2-7.4                           amd64        Amateur Packet Radio Node program
ii  libjs-node-uuid                                             1.4.0-1                             all          simple, fast generation of RFC4122 UUIDs - JavaScript library
ii  node                                                        0.3.2-7.4                           all          Amateur Packet Radio Node program (transitional package)
ii  node-abbrev                                                 1.0.5-2                             all          Get unique abbreviations for a set of strings - Node.js module
ii  node-ansi                                                   0.3.0-2                             all          Advanced ANSI formatting tool for Node.js
ii  node-ansi-color-table                                       1.0.0-1                             all          Color and format tables for ansi output - Node.js module
ii  node-archy                                                  0.0.2-1                             all          Pretty-print nested hierarchies module for Node.js
ii  node-async                                                  0.8.0-1                             all          higher-order functions and common patterns for asynchronous Javascript
ii  node-block-stream                                           0.0.7-1                             all          Stream of fixed-size blocks, with zero-padding when necessary
ii  node-combined-stream                                        0.0.5-1                             all          Append streams one after another - module for Node.js
ii  node-cookie-jar                                             0.3.1-1                             all          Cookie handling for HTTP clients - module for Node.js
ii  node-delayed-stream                                         0.0.5-1                             all          Buffer stream events for later handling - module for Node.js
ii  node-forever-agent                                          0.5.1-1                             all          HTTP agent supporting keep-alive requests - module for Node.js
ii  node-form-data                                              0.1.0-1                             all          Create multipart/form-data streams module for Node.js
ii  node-fstream                                                0.1.24-1                            all          Advanced filesystem streaming tools for Node.js
ii  node-fstream-ignore                                         0.0.6-2                             all          Directory reader configurable by .ignore module for Node.js
ii  node-github-url-from-git                                    1.1.1-1                             all          Convert github git or gist url to an http url - Node.js module
ii  node-glob                                                   4.0.5-1                             all          glob functionality for Node.js
ii  node-graceful-fs                                            3.0.2-1                             all          drop-in replacement improving the Node.js fs module
ii  node-gyp                                                    0.12.2+ds-1                         all          Native addon build tool for Node.js
ii  node-inherits                                               2.0.1-3                             all          Exposes inherits function from Node.js environment
ii  node-ini                                                    1.1.0-1                             all          ini format parser and serializer for Node.js
ii  node-json-stringify-safe                                    5.0.0-1                             all          JSON.stringify with circular references module for Node.js
ii  node-lockfile                                               0.4.1-1                             all          Asynchronous file lock module for Node.js
ii  node-lru-cache                                              2.3.1-1                             all          least-recently-used cache object for Node.js
ii  node-mime                                                   1.3.4-1                             all          library for mime-type mapping for Node.js
ii  node-minimatch                                              1.0.0-1                             all          Convert glob expressions into RegExp objects for Node.js
ii  node-mkdirp                                                 0.5.0-1                             all          Recursively create directories - Node.js module
ii  node-mute-stream                                            0.0.4-1                             all          Pass-through stream that can be muted module for Node.js
ii  node-node-uuid                                              1.4.0-1                             all          simple, fast generation of RFC4122 UUIDs - Node module
ii  node-nopt                                                   3.0.1-1                             all          Command-line option parser for Node.js
ii  node-normalize-package-data                                 0.2.2-1                             all          Normalizes package metadata - Node.js module
ii  node-npmlog                                                 0.0.4-1                             all          Logger with custom levels and colored output for Node.js
ii  node-once                                                   1.1.1-1                             all          Run a function only once with this module for Node.js
ii  node-osenv                                                  0.1.0-1                             all          Environment settings lookup module for Node.js
ii  node-qs                                                     2.2.4-1                             all          Parse, stringify query strings for Node.js
ii  node-read                                                   1.0.5-1                             all          Read user input from stdin module for Node.js
ii  node-read-package-json                                      1.2.4-1                             all          Read package.json for npm module for Node.js
ii  node-request                                                2.26.1-1                            all          simplified HTTP request client module for Node.js
ii  node-retry                                                  0.6.0-1                             all          Retry strategies for failed operations module for Node.js
ii  node-rimraf                                                 2.2.8-1                             all          Deep deletion (like rm -rf) module for Node.js
ii  node-semver                                                 2.1.0-2                             all          Semantic Versioning for Node.js
ii  node-sha                                                    1.2.3-1                             all          Check and get file or stream hashes - module for Node.js
ii  node-sigmund                                                1.0.0-1                             all          Quick and dirty signatures for Objects module for Node.js
ii  node-slide                                                  1.1.4-1                             all          Simple chain and asyncMap flow control module for Node.js
ii  node-tar                                                    1.0.3-2                             all          read and write portable tar archives module for Node.js
ii  node-tunnel-agent                                           0.3.1-1                             all          HTTP proxy tunneling agent module for Node.js
ii  node-underscore                                             1.7.0~dfsg-1                        all          JavaScript's functional programming helper library - NodeJS
ii  node-which                                                  1.0.5-2                             all          Cross-platform 'which' module for Node.js
ii  nodejs                                                      0.10.38~dfsg-1                      amd64        evented I/O for V8 javascript
ii  nodejs-dev                                                  0.10.38~dfsg-1                      amd64        evented I/O for V8 javascript (development files)

**Comment by flipefr** [comment]
I can find the error, but is an installation problem with node so I close the issue
