### ISSUE TITLE
Can this repo be used as a client for non-ProtonMail mail?

### ISSUE THREAD

**Issue by joms** [ProtonMail/WebClient#13]
Or are there plans for this in the future?

**Comment by Manouchehri** [comment]
I don't see why not. It's all under the MIT license, so you can pretty much do whatever you want.

**Comment by jasonstockman** [comment]
The tricky part about doing this would be in modifying the underlying models and controllers to adhere to whatever email API you are connecting with. This WebClient was designed and built to consume our ProtonMail API. But yeah you could modify and adapt this to display any data source you wanted.
