### ISSUE TITLE
Safari 9 pin icon

### ISSUE THREAD

**Issue by Eitot** [ProtonMail/WebClient#21]
Please don't forget to add a pin icon for Safari 9. :-)

![iu](https://cloud.githubusercontent.com/assets/15073177/11098461/6a1a1f56-88a5-11e5-979e-42c0f41315cc.jpeg)

See here: https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW20

**Comment by jasonstockman** [comment]
I wasn't aware this existed. Thanks. We will add it.

**Comment by jasonstockman** [comment]
Added, should be live (make sure to clear your cache).

**Comment by Eitot** [comment]
I can't see it in the web client yet. Nothing in the source code either.
It's cool that you responded so quickly to this. Just a minor point, but it just improves the user experience!

**Comment by jasonstockman** [comment]
You may be cached. It's only on the homepage for now. Should be line 19.
<img width="775" alt="screen shot 2015-11-12 at 7 34 21 pm" src="https://cloud.githubusercontent.com/assets/271327/11138221/7f8fe404-8974-11e5-8efb-daaa3b7bfe30.png">

**Comment by Eitot** [comment]
Indeed. I hope you manage to implement it into the web client too.
