### ISSUE TITLE
Wobbly refresh icon

### ISSUE THREAD

**Issue by daniel-childs** [ProtonMail/WebClient#26]
The Font Awesome refresh icon wobbles when it's being rotated.

https://github.com/FortAwesome/Font-Awesome/issues/671
![screenshot](https://cloud.githubusercontent.com/assets/4240758/13649557/8d906e14-e5fb-11e5-8a1c-6363eefa942e.png)

**Comment by jasonstockman** [comment]
This is a known issue. Source is here: https://github.com/FortAwesome/Font-Awesome/issues/671

**Comment by daniel-childs** [comment]
Maybe replace the icon with equal width/height SVG? Assuming a modern browser is used, SVG rotations should be valid.

**Comment by jasonstockman** [comment]
Absolutely open to a PR with this. At the moment it's not on our radar as something to fix over new features we're building.

**Comment by Eitot** [comment]
I submitted a PR (#28). In my browser, setting the line-height of the `<button>` element seems to be enough, but I have not tested this more broadly.
