### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by clee** [ProtonMail/WebClient#6]
I'm sure many of us can figure out how to install this and get it running, but it sure would be nice to have a few lines in the README that explain the basics :)

**Comment by joms** [comment]
+1

**Comment by Posterum** [comment]
Indeed, some install instruction would be great :)

**Comment by jasonstockman** [comment]
Added some basic instructions here https://github.com/ProtonMail/WebClient/commit/b091c63a2450015c04679fdbfbeb577c969a351e. 

Won't have much time to flush them out for a while. The build is similar in style to other projects that use NPM, Bower and Grunt.

**Comment by enguerran** [comment]
Very interesting job you did with protonmail. Just one question about installation of the webclient: why do you want to `sudo` npm and bower commands as they install everything on the current directory?
I tried install it without `sudo` and it works like a charm.
